/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Starting;

import xCustomDialog.dialog_loginberhasil;
import xCustomDialog.dialog_logingagal;
import MainMenu.landingmenu;
import java.awt.Color;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import keeptoo.Drag;
import xCustomDialog.dialog_logingagaldb;

/**
 *
 * @author henry
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public void Timer() {
        Timer t2 = new Timer();
        t2.scheduleAtFixedRate(new TimerTask() {

            @Override
            public void run() {
                timenow.setText(new SimpleDateFormat("dd-MM-yyyy hh:mm:ss").format(new java.util.Date()));
            }
        }, 0, 1000);

        /// Membuat label berjalan
        Timer t3 = new Timer();
        t3.scheduleAtFixedRate(new TimerTask() {
            @Override
            public void run() {

            }
        }, 0, 80);
    }

    public LoginForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setBackground(new Color(0, 0, 0, 0));
        Timer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPasswordField1 = new javax.swing.JPasswordField();
                jScrollPane1 = new javax.swing.JScrollPane();
                jTextArea1 = new javax.swing.JTextArea();
                kGradientPanel1 = new keeptoo.KGradientPanel();
                kButton1 = new keeptoo.KButton();
                kGradientPanel2 = new keeptoo.KGradientPanel();
                jLabel4 = new javax.swing.JLabel();
                inputusername = new javax.swing.JTextField();
                jLabel6 = new javax.swing.JLabel();
                inputpassword = new javax.swing.JPasswordField();
                tombolregistrasi = new keeptoo.KButton();
                tombollogin = new keeptoo.KButton();
                labelcp = new javax.swing.JLabel();
                jLabel8 = new javax.swing.JLabel();
                tombolclose1 = new javax.swing.JLabel();
                timenow = new javax.swing.JLabel();
                timenow1 = new javax.swing.JLabel();

                jPasswordField1.setText("jPasswordField1");

                jTextArea1.setColumns(20);
                jTextArea1.setRows(5);
                jScrollPane1.setViewportView(jTextArea1);

                javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
                kGradientPanel1.setLayout(kGradientPanel1Layout);
                kGradientPanel1Layout.setHorizontalGroup(
                        kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 380, Short.MAX_VALUE)
                );
                kGradientPanel1Layout.setVerticalGroup(
                        kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 280, Short.MAX_VALUE)
                );

                kButton1.setText("kButton1");

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setUndecorated(true);

                kGradientPanel2.setkBorderRadius(50);
                kGradientPanel2.setkEndColor(new java.awt.Color(239, 50, 217));
                kGradientPanel2.setkGradientFocus(800);
                kGradientPanel2.setkStartColor(new java.awt.Color(137, 255, 253));
                kGradientPanel2.setkTransparentControls(false);
                kGradientPanel2.setOpaque(false);
                kGradientPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
                        public void mouseDragged(java.awt.event.MouseEvent evt) {
                                kGradientPanel2MouseDragged(evt);
                        }
                });
                kGradientPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mousePressed(java.awt.event.MouseEvent evt) {
                                kGradientPanel2MousePressed(evt);
                        }
                });

                jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jLabel4.setForeground(new java.awt.Color(255, 255, 255));
                jLabel4.setText("username");

                inputusername.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
                inputusername.setOpaque(false);
                inputusername.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                inputusernameActionPerformed(evt);
                        }
                });

                jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jLabel6.setForeground(new java.awt.Color(255, 255, 255));
                jLabel6.setText("password");

                inputpassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
                inputpassword.setOpaque(false);
                inputpassword.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                inputpasswordActionPerformed(evt);
                        }
                });

                tombolregistrasi.setText("Registrasi");
                tombolregistrasi.setBorderPainted(false);
                tombolregistrasi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                tombolregistrasi.setkBorderRadius(30);
                tombolregistrasi.setkEndColor(new java.awt.Color(255, 102, 102));
                tombolregistrasi.setkIndicatorThickness(0);
                tombolregistrasi.setkStartColor(new java.awt.Color(204, 0, 204));
                tombolregistrasi.setOpaque(false);
                tombolregistrasi.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                tombolregistrasiActionPerformed(evt);
                        }
                });

                tombollogin.setText("Login");
                tombollogin.setBorderPainted(false);
                tombollogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                tombollogin.setkBackGroundColor(new java.awt.Color(204, 0, 204));
                tombollogin.setkBorderRadius(30);
                tombollogin.setkEndColor(new java.awt.Color(0, 204, 0));
                tombollogin.setOpaque(false);
                tombollogin.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                tombolloginActionPerformed(evt);
                        }
                });

                labelcp.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
                labelcp.setForeground(new java.awt.Color(255, 255, 255));
                labelcp.setText("Copyright © Developed Universitas Dinamika");
                labelcp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                labelcp.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                labelcpMouseClicked(evt);
                        }
                });

                jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
                jLabel8.setForeground(new java.awt.Color(255, 255, 255));
                jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/lg.png"))); // NOI18N

                tombolclose1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
                tombolclose1.setForeground(new java.awt.Color(255, 255, 255));
                tombolclose1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconclose50.png"))); // NOI18N
                tombolclose1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                tombolclose1.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                tombolclose1MouseClicked(evt);
                        }
                });

                timenow.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
                timenow.setText("Waktu Saat Ini");

                timenow1.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
                timenow1.setText("Waktu Saat Ini");

                javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
                kGradientPanel2.setLayout(kGradientPanel2Layout);
                kGradientPanel2Layout.setHorizontalGroup(
                        kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(kGradientPanel2Layout.createSequentialGroup()
                                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(kGradientPanel2Layout.createSequentialGroup()
                                                .addGap(139, 139, 139)
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(tombolclose1))
                                        .addGroup(kGradientPanel2Layout.createSequentialGroup()
                                                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(kGradientPanel2Layout.createSequentialGroup()
                                                                .addGap(23, 23, 23)
                                                                .addComponent(labelcp))
                                                        .addGroup(kGradientPanel2Layout.createSequentialGroup()
                                                                .addGap(37, 37, 37)
                                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(kGradientPanel2Layout.createSequentialGroup()
                                                                .addGap(37, 37, 37)
                                                                .addComponent(inputpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(kGradientPanel2Layout.createSequentialGroup()
                                                                .addGap(37, 37, 37)
                                                                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(inputusername, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(kGradientPanel2Layout.createSequentialGroup()
                                                                .addGap(52, 52, 52)
                                                                .addComponent(tombollogin, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(121, 121, 121)
                                                                .addComponent(tombolregistrasi, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(kGradientPanel2Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(timenow1)))
                                                .addGap(0, 39, Short.MAX_VALUE)))
                                .addContainerGap())
                        .addGroup(kGradientPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(timenow)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                kGradientPanel2Layout.setVerticalGroup(
                        kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(kGradientPanel2Layout.createSequentialGroup()
                                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(kGradientPanel2Layout.createSequentialGroup()
                                                .addGap(13, 13, 13)
                                                .addComponent(jLabel8))
                                        .addComponent(tombolclose1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addGap(6, 6, 6)
                                .addComponent(inputusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(inputpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tombolregistrasi, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                                        .addComponent(tombollogin, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(timenow1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(timenow, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                                .addComponent(labelcp)
                                .addContainerGap())
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(kGradientPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(kGradientPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void labelcpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelcpMouseClicked

    }//GEN-LAST:event_labelcpMouseClicked

    private void methodlogin() {
        PreparedStatement ps;
        ResultSet rs;
        String nama = inputusername.getText();
        String pass = String.valueOf((inputpassword.getPassword()));

        if (nama.equals("") && pass.equals("")) {
            JOptionPane.showMessageDialog(this, "Isi Semua Field Terlebih Dahulu");
        } else if (nama.equals("")) {
            JOptionPane.showMessageDialog(this, "Field Nama Masih Kosong");
        } else if (pass.equals("")) {
            JOptionPane.showMessageDialog(this, "Field Password Masih Kosong");
        } else {
            String query = "SELECT * FROM `petugas` WHERE `username` =? AND`password` =?";

            try {
                ps = koneksidb.getConnection().prepareStatement(query);
                ps.setString(1, nama);
                ps.setString(2, pass);
                rs = ps.executeQuery();

                if (rs.next()) {
                    landingmenu lm = new landingmenu(rs.getString("noktp"));
                    lm.setVisible(true);
                    lm.pack();
                    lm.setLocationRelativeTo(null);
                    lm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

                    dialog_loginberhasil y = new dialog_loginberhasil(rs.getString("nama_petugas"), rs.getString("username"));
                    y.setVisible(true);
                    y.pack();
                    y.setLocationRelativeTo(null);
                    y.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    this.dispose();

                } else {
                    dialog_logingagal gagal = new dialog_logingagal();
                    gagal.setVisible(true);
                    gagal.pack();
                    gagal.setLocationRelativeTo(null);
                    gagal.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

                }
            } catch (SQLException ex) {
                dialog_logingagaldb gagal = new dialog_logingagaldb();
                gagal.setVisible(true);
                gagal.pack();
                gagal.setLocationRelativeTo(null);
                gagal.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                System.out.println(ex);
            }
        }
    }
    private void tombolloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolloginActionPerformed
        // TODO add your handling code here:
        methodlogin();
    }//GEN-LAST:event_tombolloginActionPerformed

    private void inputusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputusernameActionPerformed

    private void tombolregistrasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolregistrasiActionPerformed
        // TODO add your handling code here:
        RegisterForm rf = new RegisterForm();
        rf.setVisible(true);
        rf.pack();
        rf.setLocationRelativeTo(null);
        rf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();


    }//GEN-LAST:event_tombolregistrasiActionPerformed

    private void tombolclose1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolclose1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_tombolclose1MouseClicked

    private void inputpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputpasswordActionPerformed
        // TODO add your handling code here:
        methodlogin();
    }//GEN-LAST:event_inputpasswordActionPerformed

        private void kGradientPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel2MousePressed
                // TODO add your handling code here:
		new Drag(kGradientPanel2).onPress(evt);
        }//GEN-LAST:event_kGradientPanel2MousePressed

        private void kGradientPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel2MouseDragged
                // TODO add your handling code here:
		new Drag(kGradientPanel2).moveWindow(evt);
        }//GEN-LAST:event_kGradientPanel2MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JPasswordField inputpassword;
        private javax.swing.JTextField inputusername;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JPasswordField jPasswordField1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTextArea jTextArea1;
        private keeptoo.KButton kButton1;
        private keeptoo.KGradientPanel kGradientPanel1;
        private keeptoo.KGradientPanel kGradientPanel2;
        private javax.swing.JLabel labelcp;
        private javax.swing.JLabel timenow;
        private javax.swing.JLabel timenow1;
        private javax.swing.JLabel tombolclose1;
        private keeptoo.KButton tombollogin;
        private keeptoo.KButton tombolregistrasi;
        // End of variables declaration//GEN-END:variables
}
