/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Starting;

import xCustomDialog.dialog_pendaftaranok;
import java.awt.Color;
import java.time.format.DateTimeFormatter;
import java.time.LocalDateTime;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import keeptoo.Drag;

/**
 *
 * @author henry
 */
public class RegisterForm extends javax.swing.JFrame {

    /**
     * Creates new form RegisterForm
     */
    public void TimerFull() {
        java.util.Timer t2 = new java.util.Timer();
        t2.scheduleAtFixedRate(new TimerTask() {
            @Override
            public void run() {
                timenow.setText(new SimpleDateFormat("dd-MM-yyyy hh:mm:ss").format(new java.util.Date()));
            }
        }, 0, 1000);
        /// Membuat label berjalan
        java.util.Timer t3 = new java.util.Timer();
        t3.scheduleAtFixedRate(new TimerTask() {
            @Override
            public void run() {

            }
        }, 0, 80);
    }

    public RegisterForm() {

        initComponents();
        this.setBackground(new Color(0, 0, 0, 0));
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        String waktu = String.valueOf(dtf.format(now));
        TimerFull();

        Runnable waktunow = new Runnable() {
            public void run() {
//              tampilwaktu.setText(waktu);
            }
        };

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                kGradientPanel1 = new keeptoo.KGradientPanel();
                jLabel7 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                labelpassword = new javax.swing.JLabel();
                jLabel10 = new javax.swing.JLabel();
                jLabel13 = new javax.swing.JLabel();
                jLabel12 = new javax.swing.JLabel();
                kliktoregister = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                inputnama = new javax.swing.JTextField();
                inputusername = new javax.swing.JTextField();
                inputTelp = new javax.swing.JTextField();
                inputpassword = new javax.swing.JPasswordField();
                inputtoken = new javax.swing.JPasswordField();
                inputAlamat = new javax.swing.JTextField();
                timenow = new javax.swing.JTextField();
                jLabel9 = new javax.swing.JLabel();
                jLabel15 = new javax.swing.JLabel();
                buttonsubmit = new javax.swing.JLabel();
                jLabel11 = new javax.swing.JLabel();
                inputKtp = new javax.swing.JTextField();
                jPanel1 = new javax.swing.JPanel();
                jLabel8 = new javax.swing.JLabel();
                buttonback = new javax.swing.JLabel();
                jLabel14 = new javax.swing.JLabel();
                kGradientPanel2 = new keeptoo.KGradientPanel();
                tombolclose = new javax.swing.JLabel();
                tombolminim = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setUndecorated(true);

                kGradientPanel1.setkBorderRadius(0);
                kGradientPanel1.setkEndColor(new java.awt.Color(137, 255, 253));
                kGradientPanel1.setkGradientFocus(1000);
                kGradientPanel1.setkStartColor(new java.awt.Color(97, 144, 232));

                jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                jLabel7.setForeground(new java.awt.Color(255, 255, 255));
                jLabel7.setText("Nama    ");

                jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                jLabel4.setForeground(new java.awt.Color(255, 255, 255));
                jLabel4.setText("Username");

                labelpassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                labelpassword.setForeground(new java.awt.Color(255, 255, 255));
                labelpassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/password.png"))); // NOI18N
                labelpassword.setText("Password ");

                jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                jLabel10.setForeground(new java.awt.Color(255, 255, 255));
                jLabel10.setText("Token      :");

                jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                jLabel13.setForeground(new java.awt.Color(255, 255, 255));
                jLabel13.setText("Alamat");

                jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                jLabel12.setForeground(new java.awt.Color(255, 255, 255));
                jLabel12.setText("Tanggal Daftar :");

                kliktoregister.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
                kliktoregister.setForeground(new java.awt.Color(255, 255, 255));
                kliktoregister.setText("Token dapat diminta ke Admin Persewaan");
                kliktoregister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                kliktoregister.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                kliktoregisterMouseClicked(evt);
                        }
                });

                jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                jLabel5.setForeground(new java.awt.Color(255, 255, 255));
                jLabel5.setText("Form Registrasi");

                inputnama.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
                inputnama.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
                inputnama.setOpaque(false);

                inputusername.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
                inputusername.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
                inputusername.setOpaque(false);
                inputusername.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                inputusernameActionPerformed(evt);
                        }
                });

                inputTelp.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
                inputTelp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
                inputTelp.setOpaque(false);

                inputpassword.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
                inputpassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
                inputpassword.setOpaque(false);

                inputtoken.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
                inputtoken.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
                inputtoken.setOpaque(false);

                inputAlamat.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
                inputAlamat.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
                inputAlamat.setOpaque(false);

                timenow.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
                timenow.setForeground(new java.awt.Color(255, 255, 255));
                timenow.setText("OTOMATIS");
                timenow.setBorder(null);
                timenow.setOpaque(false);

                jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
                jLabel9.setForeground(new java.awt.Color(255, 255, 255));
                jLabel9.setText("Reset All");
                jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jLabel9MouseClicked(evt);
                        }
                });

                jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                jLabel15.setForeground(new java.awt.Color(255, 255, 255));
                jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/email.png"))); // NOI18N
                jLabel15.setText("Kontak");

                buttonsubmit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                buttonsubmit.setForeground(new java.awt.Color(255, 255, 255));
                buttonsubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tombolcontinue50px.png"))); // NOI18N
                buttonsubmit.setText("Submit");
                buttonsubmit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                buttonsubmit.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                buttonsubmitMouseClicked(evt);
                        }
                });

                jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                jLabel11.setForeground(new java.awt.Color(255, 255, 255));
                jLabel11.setText("No KTP");

                inputKtp.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
                inputKtp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
                inputKtp.setOpaque(false);

                javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
                kGradientPanel1.setLayout(kGradientPanel1Layout);
                kGradientPanel1Layout.setHorizontalGroup(
                        kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(inputKtp, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(inputtoken, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(kliktoregister)))
                                                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGap(289, 289, 289))
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                                                                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                        .addComponent(inputusername, javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(inputnama))
                                                                                .addGap(83, 83, 83)))
                                                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(timenow)
                                                                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                                        .addComponent(inputAlamat)
                                                                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(209, 209, 209)))))
                                                .addGap(94, 94, 94))
                                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(labelpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel9)
                                                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                                .addComponent(inputpassword)
                                                                .addGap(178, 178, 178)))
                                                .addComponent(buttonsubmit)
                                                .addGap(179, 179, 179))
                                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                .addComponent(inputTelp, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                );
                kGradientPanel1Layout.setVerticalGroup(
                        kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addComponent(jLabel10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(inputtoken, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(kliktoregister))
                                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(inputKtp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel13)
                                                        .addComponent(jLabel7))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(inputAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(inputnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(11, 11, 11)
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(inputusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(14, 14, 14))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(timenow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                .addGap(48, 48, 48)
                                                .addComponent(buttonsubmit)
                                                .addGap(154, 154, 154))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel15)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(inputTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(22, 22, 22)
                                                .addComponent(labelpassword)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                                .addComponent(inputpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(65, 65, 65))
                                                        .addComponent(jLabel9))
                                                .addGap(81, 81, 81))))
                );

                jPanel1.setBackground(new java.awt.Color(255, 255, 255));

                jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
                jLabel8.setForeground(new java.awt.Color(255, 255, 255));
                jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/lg.png"))); // NOI18N
                jLabel8.setText("Form Registrasi");

                buttonback.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                buttonback.setForeground(new java.awt.Color(255, 255, 255));
                buttonback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kembalicl.png"))); // NOI18N
                buttonback.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                buttonbackMouseClicked(evt);
                        }
                });

                jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                jLabel14.setForeground(new java.awt.Color(204, 204, 204));
                jLabel14.setText("Kembali");

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 165, Short.MAX_VALUE)
                                .addGap(31, 31, 31))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(50, 50, 50)
                                                .addComponent(buttonback))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(78, 78, 78)
                                                .addComponent(jLabel14)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonback, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14)
                                .addContainerGap())
                );

                kGradientPanel2.setkBorderRadius(0);
                kGradientPanel2.setkEndColor(new java.awt.Color(239, 50, 217));
                kGradientPanel2.setkGradientFocus(1000);
                kGradientPanel2.setkStartColor(new java.awt.Color(137, 255, 253));
                kGradientPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
                        public void mouseDragged(java.awt.event.MouseEvent evt) {
                                kGradientPanel2MouseDragged(evt);
                        }
                });
                kGradientPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mousePressed(java.awt.event.MouseEvent evt) {
                                kGradientPanel2MousePressed(evt);
                        }
                });

                tombolclose.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
                tombolclose.setForeground(new java.awt.Color(255, 255, 255));
                tombolclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconclose50.png"))); // NOI18N
                tombolclose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                tombolclose.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                tombolcloseMouseClicked(evt);
                        }
                });

                tombolminim.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
                tombolminim.setForeground(new java.awt.Color(255, 255, 255));
                tombolminim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Starting/iconminimize.png"))); // NOI18N
                tombolminim.setText("\n");
                tombolminim.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                tombolminim.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                tombolminimMouseClicked(evt);
                        }
                });

                jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                jLabel2.setForeground(new java.awt.Color(255, 255, 255));
                jLabel2.setText("Sistem Informasi Persewaan Mobil");

                javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
                kGradientPanel2.setLayout(kGradientPanel2Layout);
                kGradientPanel2Layout.setHorizontalGroup(
                        kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(tombolminim, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tombolclose)
                                .addGap(2, 2, 2))
                );
                kGradientPanel2Layout.setVerticalGroup(
                        kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(kGradientPanel2Layout.createSequentialGroup()
                                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tombolminim)
                                        .addComponent(tombolclose))
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(kGradientPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 991, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(kGradientPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, Short.MAX_VALUE)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents


    private void tombolminimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolminimMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_tombolminimMouseClicked

    private void tombolcloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolcloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_tombolcloseMouseClicked

    private void buttonbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonbackMouseClicked
        // TODO add your handling code here:
        this.dispose();
        LoginForm x = new LoginForm();
        x.setVisible(true);
    }//GEN-LAST:event_buttonbackMouseClicked

    private void buttonsubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonsubmitMouseClicked
        // TODO add your handling code here:
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();

	
	String noKtp = inputKtp.getText();
        String token = String.valueOf(inputtoken.getPassword());
        String nama = inputnama.getText();
        String username = inputusername.getText();
        String telp = inputTelp.getText();
        String password = String.valueOf(inputpassword.getPassword());
        String tanggal = String.valueOf(dtf.format(now));
        String alamat = inputAlamat.getText();
        String id = null;
	if (noKtp.equals("")) {
            JOptionPane.showMessageDialog(this, "No KTP Tidak Boleh Kosong");
        }
        if (nama.equals("")) {
            JOptionPane.showMessageDialog(this, "Nama Tidak Boleh Kosong");
        }
        if (username.equals("")) {
            JOptionPane.showMessageDialog(this, "Username Tidak Boleh Kosong");
        }
        if (telp.equals("")) {
            JOptionPane.showMessageDialog(this, "Telp Tidak Boleh Kosong");
        }
        if (password.equals("")) {
            JOptionPane.showMessageDialog(this, "Password Tidak Boleh Kosong");
        }
        if (tanggal.equals("")) {
            JOptionPane.showMessageDialog(this, "Tanggal Daftar Tidak Boleh Kosong");
        }
        if (alamat.equals("")) {
            JOptionPane.showMessageDialog(this, "Kontak Tidak Boleh Kosong");
        }
        PreparedStatement ps;                   //1     //2         //3                //4    //5         //6
        String query = "INSERT INTO `petugas`(`NOKTP`, `USERNAME`, `NAMA_PETUGAS`, `TANGGAL_DAFTAR`, `PASSWORD`, `KONTAK`,`ALAMAT_PETUGAS`) VALUES (?,?,?,?,?,?,?)";
        if (token.equalsIgnoreCase("sewayuk") || token.equalsIgnoreCase("Sewamobil") || token.equalsIgnoreCase("persewaan2000")) {

            try {
                ps = koneksidb.getConnection().prepareStatement(query);
                ps.setString(1, noKtp);
                ps.setString(2, username);
                ps.setString(3, nama);
                ps.setString(4, tanggal);
                ps.setString(5, password);
                ps.setString(6, telp);
		ps.setString(7, alamat);
                if (ps.executeUpdate() > 0) {
//                    new tampilsementara(nama, username, email, password, tanggal, hp).setVisible(true);
                    dialog_pendaftaranok ok = new dialog_pendaftaranok();
                    ok.setVisible(true);
                    ok.pack();
                    ok.setLocationRelativeTo(null);
                    ok.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                }

            } catch (SQLException ex) {
                Logger.getLogger(RegisterForm.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Gagal Mendaftar");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Token Yang Anda Masukkan Salah !!!");
        }

    }//GEN-LAST:event_buttonsubmitMouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        inputtoken.setText("");
        inputnama.setText("");
        inputTelp.setText("");
        inputAlamat.setText("");
        inputpassword.setText("");
	inputKtp.setText("");
	inputusername.setText("");
    }//GEN-LAST:event_jLabel9MouseClicked

    private void inputusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputusernameActionPerformed

    private void kliktoregisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kliktoregisterMouseClicked

    }//GEN-LAST:event_kliktoregisterMouseClicked

        private void kGradientPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel2MousePressed
                // TODO add your handling code here:
		new Drag(kGradientPanel2).onPress(evt);
        }//GEN-LAST:event_kGradientPanel2MousePressed

        private void kGradientPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel2MouseDragged
                // TODO add your handling code here:
		new Drag(kGradientPanel2).moveWindow(evt);
        }//GEN-LAST:event_kGradientPanel2MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForm().setVisible(true);
            }
        });
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel buttonback;
        private javax.swing.JLabel buttonsubmit;
        private javax.swing.JTextField inputAlamat;
        private javax.swing.JTextField inputKtp;
        private javax.swing.JTextField inputTelp;
        private javax.swing.JTextField inputnama;
        private javax.swing.JPasswordField inputpassword;
        private javax.swing.JPasswordField inputtoken;
        private javax.swing.JTextField inputusername;
        private javax.swing.JLabel jLabel10;
        private javax.swing.JLabel jLabel11;
        private javax.swing.JLabel jLabel12;
        private javax.swing.JLabel jLabel13;
        private javax.swing.JLabel jLabel14;
        private javax.swing.JLabel jLabel15;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JPanel jPanel1;
        private keeptoo.KGradientPanel kGradientPanel1;
        private keeptoo.KGradientPanel kGradientPanel2;
        private javax.swing.JLabel kliktoregister;
        private javax.swing.JLabel labelpassword;
        private javax.swing.JTextField timenow;
        private javax.swing.JLabel tombolclose;
        private javax.swing.JLabel tombolminim;
        // End of variables declaration//GEN-END:variables
}
