/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainMenu;

import Starting.*;
import xCustomDialog.dialog_loginberhasil;
import xCustomDialog.dialog_logingagal;
import MainMenu.landingmenu;
import java.awt.Color;
import java.awt.Font;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import xCustomDialog.dialog_logingagaldb;

/**
 *
 * @author henry
 */
public class LihatKode extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public void Timer() {
        Timer t2 = new Timer();
        t2.scheduleAtFixedRate(new TimerTask() {

            @Override
            public void run() {
                timenow.setText(new SimpleDateFormat("dd-MM-yyyy hh:mm:ss").format(new java.util.Date()));
            }
        }, 0, 1000);

        /// Membuat label berjalan
        Timer t3 = new Timer();
        t3.scheduleAtFixedRate(new TimerTask() {
            @Override
            public void run() {

            }
        }, 0, 80);
    }

    public LihatKode() {
        initComponents();
        this.setLocationRelativeTo(null);
        Timer();
        tampilkodebarang.getTableHeader().setFont(new Font("Montserrat", Font.PLAIN, 12));
        tampilkodebarang.getTableHeader().setOpaque(false);
        tampilkodebarang.getTableHeader().setBackground(new Color(32, 136, 203));
        tampilkodebarang.getTableHeader().setForeground(new Color(255, 255, 255));
        tampilkodebarang.setRowHeight(25);
        updatedbkodebarang();
    }

    private void updatedbkodebarang() {
        PreparedStatement ps;
        DefaultTableModel axyz = (DefaultTableModel) tampilkodebarang.getModel();
        String queryx = "SELECT `Kode Barang`, `Nama Item`, `Vendor`, `Harga Jual`, `Harga Vendor`, `Stok`, `kodeunik` FROM `databarang` WHERE 1";
        int nomer = tampilkodebarang.getRowCount() + 1;
        axyz.getDataVector().removeAllElements();
        axyz.fireTableDataChanged();
      
        if (nomer != 1) {
            for (int j = 0; j < nomer; j++) {
                axyz.removeRow(j);
            }
        }
        try {
            ps = koneksidb.getConnection().prepareStatement(queryx);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                String tlkodebarang = rs.getString("Kode Barang");
                String tlnamabarang = rs.getString("Nama Item");
                String tlvendor = rs.getString("Vendor");
                String tlharga = rs.getString("Harga Jual");
                String tlstok = rs.getString("Stok");
                String tlkodeunik = rs.getString("kodeunik");
                String tlhargavendor = rs.getString("Harga Vendor");


                Object[] barang2 = new Object[7];
                barang2[0] = tlnamabarang;
                barang2[1] = tlkodebarang;
                barang2[2] = tlvendor;
                barang2[3] = tlharga;
                barang2[4] = tlhargavendor;
                barang2[5] = tlstok;
                axyz.addRow(barang2);

            }
            System.out.println("Update DB Tampil Kode Berhasil !");
        } catch (Exception er) {
            System.err.println(er);
            System.out.println("Gagal di Method updatedb()");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        kButton1 = new keeptoo.KButton();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        timenow = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tampilkodebarang = new javax.swing.JTable();
        tomboladdtoList1 = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        kButton1.setText("kButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel2.setkBorderRadius(0);
        kGradientPanel2.setkEndColor(new java.awt.Color(239, 50, 217));
        kGradientPanel2.setkGradientFocus(1000);
        kGradientPanel2.setkStartColor(new java.awt.Color(137, 255, 253));
        kGradientPanel2.setkTransparentControls(false);
        kGradientPanel2.setOpaque(false);

        timenow.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        timenow.setText("Waktu Saat Ini");

        tampilkodebarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Barang", "Kode ", "Vendor", "Harga Jual", "Harga Vendor", "Stok"
            }
        ));
        tampilkodebarang.setFocusable(false);
        tampilkodebarang.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tampilkodebarang.setRowHeight(25);
        tampilkodebarang.setSelectionBackground(new java.awt.Color(0, 204, 204));
        tampilkodebarang.setShowVerticalLines(false);
        tampilkodebarang.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(tampilkodebarang);

        tomboladdtoList1.setBackground(new java.awt.Color(255, 255, 255));
        tomboladdtoList1.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        tomboladdtoList1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-refresh-65.png"))); // NOI18N
        tomboladdtoList1.setText("Refresh");
        tomboladdtoList1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tomboladdtoList1.setOpaque(true);
        tomboladdtoList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tomboladdtoList1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tomboladdtoList1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(timenow)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(timenow, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tomboladdtoList1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tomboladdtoList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tomboladdtoList1MouseClicked
        // TODO add your handling code here:
        updatedbkodebarang();
    }//GEN-LAST:event_tomboladdtoList1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LihatKode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LihatKode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LihatKode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LihatKode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LihatKode().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    private keeptoo.KButton kButton1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JTable tampilkodebarang;
    private javax.swing.JLabel timenow;
    private javax.swing.JLabel tomboladdtoList1;
    // End of variables declaration//GEN-END:variables
}
